version: '3'

services:
  db:
    image: 'postgres:14'
    container_name: 'db'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=currency_expense_tracker_microservice

  lb:
    build:
      context: .
      dockerfile: DockerfileLB
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/currency_expense_tracker_microservice
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=postgres
      - JDBC_DRIVER=org.postgresql.Driver
    container_name: lb
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/currency_expense_tracker_microservice?currentSchema=app
      - JDBC_USER=postgres
      - JDBC_PASSWORD=postgres
      - JDBC_DRIVER=org.postgresql.Driver
    container_name: 'java-app'
    ports:
      - 8081:8080
    depends_on:
      - db
      - lb